IA-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ia bills votes --realtime"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 3,9,12,18 * * ?
    - cron: 0 4 * * ?
  timeout_minutes: 360
  next_tasks:
    - IA-text

IA-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ia"
  enabled: true
  environment: scrapers

IA-events:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ia events"
  enabled: true
  environment: scrapers
  triggers:
    - cron: 45 2 * * ?
  timeout_minutes: 60
